export const endPoint = {
    adminLogin: '/admin/log-in',
    adminLogout: '/admin/log-out',
    adminRegister: '/admin/make-account',
    sendNotify : '/admin/send-notify',
    login: "/user/login",
    register: "/user/register",
    logout: "/user/logout",
    sliders: '/sliders',
    colleges: '/colleges',
    collegeSpeciality: '/college/specialty',
    collegeSubject: '/college/subject',
    dawrat: '/user/exams/show',
    exam: "/user/exams/exam",
    calculate: "/user/exams/calculate",
}